version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels: [ ]
    schedule:
      interval: monthly
      time: 17:00
    groups:
      github-actions:
        patterns:
          - '*'